services:
    web:
        build: .
        container_name: django_auth
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code
            - static_volume:/code/backend/staticfiles
            - media_volume:/code/media
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:15
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/proxy_params:/etc/nginx/proxy_params
            - static_volume:/code/backend/staticfiles
            - media_volume:/code/media
        depends_on:
            - web


volumes:
    postgres_data:
    static_volume:
    media_volume: